import { useState } from 'react';
import { FileText, Download, Calendar, CheckSquare, Square, AlertCircle } from 'lucide-react';
import { motion } from 'motion/react';
import { useInsuranceReport, type ReportConfig, type InsuranceReport } from '../../hooks/useInsuranceReport';
import { cn } from '../../utils/utils';

interface InsuranceReportGeneratorProps {
  driverId: string;
  driverName: string;
  driverEmail: string;
}

export function InsuranceReportGenerator({ driverId, driverName, driverEmail }: InsuranceReportGeneratorProps) {
  const { isGenerating, error, generateReport, clearError } = useInsuranceReport();
  
  const [startDate, setStartDate] = useState(() => {
    const date = new Date();
    date.setMonth(date.getMonth() - 3); // Default to 3 months ago
    return date.toISOString().split('T')[0];
  });
  
  const [endDate, setEndDate] = useState(() => {
    return new Date().toISOString().split('T')[0];
  });
  
  const [includeTrips, setIncludeTrips] = useState(true);
  const [includeCrashEvents, setIncludeCrashEvents] = useState(true);
  const [includeScoreHistory, setIncludeScoreHistory] = useState(true);
  const [format, setFormat] = useState<'pdf' | 'csv'>('pdf');
  const [generatedReport, setGeneratedReport] = useState<InsuranceReport | null>(null);
  const [showPreview, setShowPreview] = useState(false);

  const validateForm = (): string | null => {
    if (!startDate || !endDate) {
      return 'Please select both start and end dates';
    }
    
    const start = new Date(startDate);
    const end = new Date(endDate);
    
    if (start > end) {
      return 'Start date must be before end date';
    }
    
    if (end > new Date()) {
      return 'End date cannot be in the future';
    }
    
    return null;
  };

  const handleGenerate = async () => {
    clearError();
    
    const validationError = validateForm();
    if (validationError) {
      alert(validationError);
      return;
    }

    const config: ReportConfig = {
      driverId,
      driverName,
      driverEmail,
      dateRange: {
        start: startDate,
        end: endDate
      },
      includeTrips,
      includeCrashEvents,
      includeScoreHistory,
      format
    };

    try {
      const report = await generateReport(config);
      setGeneratedReport(report);
      setShowPreview(true);
    } catch (err) {
      console.error('Report generation failed:', err);
    }
  };

  const handleDownload = () => {
    if (!generatedReport) return;

    // Create a simple text representation for download
    const content = `
INSURANCE SAFETY REPORT
Generated: ${new Date(generatedReport.generatedAt).toLocaleString()}
Verification Code: ${generatedReport.verificationCode}

DRIVER INFORMATION
Name: ${generatedReport.driverInfo.name}
Email: ${generatedReport.driverInfo.email}
Driver ID: ${generatedReport.driverInfo.driverId}

REPORT PERIOD
From: ${new Date(generatedReport.dateRange.start).toLocaleDateString()}
To: ${new Date(generatedReport.dateRange.end).toLocaleDateString()}

SUMMARY STATISTICS
Total Distance: ${generatedReport.summary.totalDistance.toFixed(2)} km
Total Trips: ${generatedReport.summary.totalTrips}
Average Speed: ${generatedReport.summary.averageSpeed.toFixed(2)} km/h
Safety Score: ${generatedReport.summary.safetyScore}
Crash Count: ${generatedReport.summary.crashCount}

${generatedReport.trips.length > 0 ? `
TRIP DETAILS
${generatedReport.trips.map(trip => `
- Date: ${trip.date}
  Distance: ${trip.distance.toFixed(2)} km
  Duration: ${Math.floor(trip.duration / 60)} minutes
  Safety Score: ${trip.safetyScore}
`).join('\n')}
` : ''}

${generatedReport.safetyScoreHistory.length > 0 ? `
SAFETY SCORE HISTORY
${generatedReport.safetyScoreHistory.map(entry => `
- ${new Date(entry.date).toLocaleDateString()}: ${entry.score}
`).join('\n')}
` : ''}

This report is generated by SmartSafe and can be verified using the verification code above.
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `insurance-report-${generatedReport.id}.${format === 'pdf' ? 'txt' : 'csv'}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center gap-3">
        <div className="w-10 h-10 rounded-xl bg-blue-500/10 flex items-center justify-center">
          <FileText className="w-5 h-5 text-blue-500" />
        </div>
        <div>
          <h2 className="text-xl font-black text-white">Insurance Report Generator</h2>
          <p className="text-sm text-slate-400 font-medium">
            Generate safety reports for insurance submissions
          </p>
        </div>
      </div>

      {/* Configuration Form */}
      <div className="bg-slate-900/40 backdrop-blur-xl border border-slate-800/50 rounded-2xl p-6 space-y-6">
        {/* Date Range */}
        <div>
          <label className="flex items-center gap-2 text-sm font-bold text-white mb-3">
            <Calendar className="w-4 h-4 text-emerald-500" />
            Report Period
          </label>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-2 block">
                Start Date
              </label>
              <input
                type="date"
                value={startDate}
                onChange={(e) => setStartDate(e.target.value)}
                className="w-full bg-slate-950/50 border border-slate-800/50 rounded-xl px-4 py-3 text-sm text-white focus:outline-none focus:border-emerald-500/50 transition-colors"
              />
            </div>
            <div>
              <label className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-2 block">
                End Date
              </label>
              <input
                type="date"
                value={endDate}
                onChange={(e) => setEndDate(e.target.value)}
                max={new Date().toISOString().split('T')[0]}
                className="w-full bg-slate-950/50 border border-slate-800/50 rounded-xl px-4 py-3 text-sm text-white focus:outline-none focus:border-emerald-500/50 transition-colors"
              />
            </div>
          </div>
        </div>

        {/* Data Categories */}
        <div>
          <label className="text-sm font-bold text-white mb-3 block">
            Include in Report
          </label>
          <div className="space-y-3">
            <button
              onClick={() => setIncludeTrips(!includeTrips)}
              className="flex items-center gap-3 w-full p-3 bg-slate-950/50 rounded-xl hover:bg-slate-800/50 transition-colors"
            >
              {includeTrips ? (
                <CheckSquare className="w-5 h-5 text-emerald-500" />
              ) : (
                <Square className="w-5 h-5 text-slate-500" />
              )}
              <div className="text-left">
                <div className="text-sm font-bold text-white">Trip Details</div>
                <div className="text-xs text-slate-500">Individual trip summaries with dates and distances</div>
              </div>
            </button>

            <button
              onClick={() => setIncludeCrashEvents(!includeCrashEvents)}
              className="flex items-center gap-3 w-full p-3 bg-slate-950/50 rounded-xl hover:bg-slate-800/50 transition-colors"
            >
              {includeCrashEvents ? (
                <CheckSquare className="w-5 h-5 text-emerald-500" />
              ) : (
                <Square className="w-5 h-5 text-slate-500" />
              )}
              <div className="text-left">
                <div className="text-sm font-bold text-white">Crash Events</div>
                <div className="text-xs text-slate-500">Details of detected crash incidents</div>
              </div>
            </button>

            <button
              onClick={() => setIncludeScoreHistory(!includeScoreHistory)}
              className="flex items-center gap-3 w-full p-3 bg-slate-950/50 rounded-xl hover:bg-slate-800/50 transition-colors"
            >
              {includeScoreHistory ? (
                <CheckSquare className="w-5 h-5 text-emerald-500" />
              ) : (
                <Square className="w-5 h-5 text-slate-500" />
              )}
              <div className="text-left">
                <div className="text-sm font-bold text-white">Safety Score History</div>
                <div className="text-xs text-slate-500">Historical safety score trends over time</div>
              </div>
            </button>
          </div>
        </div>

        {/* Format Selection */}
        <div>
          <label className="text-sm font-bold text-white mb-3 block">
            Export Format
          </label>
          <div className="flex gap-3">
            <button
              onClick={() => setFormat('pdf')}
              className={cn(
                "flex-1 p-4 rounded-xl border-2 transition-all",
                format === 'pdf'
                  ? "border-emerald-500 bg-emerald-500/10"
                  : "border-slate-800/50 bg-slate-950/50 hover:border-slate-700"
              )}
            >
              <div className="text-sm font-black text-white mb-1">PDF</div>
              <div className="text-xs text-slate-500">Formatted document</div>
            </button>
            <button
              onClick={() => setFormat('csv')}
              className={cn(
                "flex-1 p-4 rounded-xl border-2 transition-all",
                format === 'csv'
                  ? "border-emerald-500 bg-emerald-500/10"
                  : "border-slate-800/50 bg-slate-950/50 hover:border-slate-700"
              )}
            >
              <div className="text-sm font-black text-white mb-1">CSV</div>
              <div className="text-xs text-slate-500">Spreadsheet data</div>
            </button>
          </div>
        </div>

        {/* Error Display */}
        {error && (
          <div className="p-4 bg-red-500/10 border border-red-500/20 rounded-xl flex items-start gap-3">
            <AlertCircle className="w-5 h-5 text-red-500 shrink-0 mt-0.5" />
            <div>
              <div className="text-sm font-bold text-red-400 mb-1">Generation Failed</div>
              <div className="text-xs text-slate-400">{error}</div>
            </div>
          </div>
        )}

        {/* Generate Button */}
        <button
          onClick={handleGenerate}
          disabled={isGenerating}
          className="w-full py-4 bg-emerald-500 hover:bg-emerald-600 disabled:bg-slate-700 disabled:cursor-not-allowed text-white font-black text-sm rounded-xl transition-all flex items-center justify-center gap-2"
        >
          {isGenerating ? (
            <>
              <div className="w-4 h-4 border-2 border-white/20 border-t-white rounded-full animate-spin" />
              Generating Report...
            </>
          ) : (
            <>
              <FileText className="w-4 h-4" />
              Generate Report
            </>
          )}
        </button>
      </div>

      {/* Preview */}
      {showPreview && generatedReport && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-slate-900/40 backdrop-blur-xl border border-emerald-500/20 rounded-2xl p-6 space-y-4"
        >
          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-lg font-black text-white mb-1">Report Generated Successfully</h3>
              <p className="text-xs text-slate-400">
                Verification Code: <span className="font-mono text-emerald-400">{generatedReport.verificationCode}</span>
              </p>
            </div>
            <button
              onClick={handleDownload}
              className="flex items-center gap-2 px-4 py-2 bg-emerald-500 hover:bg-emerald-600 text-white font-bold text-sm rounded-xl transition-colors"
            >
              <Download className="w-4 h-4" />
              Download
            </button>
          </div>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 pt-4 border-t border-slate-800/50">
            <div>
              <div className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-1">
                Total Trips
              </div>
              <div className="text-xl font-black text-white">
                {generatedReport.summary.totalTrips}
              </div>
            </div>
            <div>
              <div className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-1">
                Distance
              </div>
              <div className="text-xl font-black text-white">
                {generatedReport.summary.totalDistance.toFixed(1)} km
              </div>
            </div>
            <div>
              <div className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-1">
                Safety Score
              </div>
              <div className="text-xl font-black text-emerald-400">
                {generatedReport.summary.safetyScore}
              </div>
            </div>
            <div>
              <div className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-1">
                Crashes
              </div>
              <div className="text-xl font-black text-red-400">
                {generatedReport.summary.crashCount}
              </div>
            </div>
          </div>
        </motion.div>
      )}
    </div>
  );
}
